// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgagptolbwtkkylkghop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nYWdwdG9sYnd0a2t5bGtnaG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMTgwMjgsImV4cCI6MjA1NTc5NDAyOH0.ylA_2Vc-1RDI0SvxUwxIapU9ixZ2AO84-2hloP94mI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);